version: '3.7'

services:
  nginx:
    container_name: Web_Server
    image: techwise-technologies/nginx:${NGINX_VERSION}
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR}:/var/www/html
      - ${FASTCGI_CACHE_DIR}:/tmp/cache
    ports:
      - '8080:80'
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    container_name: WordPress
    image: techwise-technologies/wordpress:${WORDPRESS_VERSION}
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    volumes:
      - ${TSUKI_PHP_CONF}:/usr/local/etc/php/conf.d/tsuki.ini
      - ${WORDPRESS_DATA_DIR}:/var/www/html
      - ${FASTCGI_CACHE_DIR}:/tmp/cache
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  redis:
    container_name: DB_Cache
    image: redis:${REDIS_VERSION}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_CONF}:/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

  db:
    container_name: DB
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - ${DB_DATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped

